os: linux
dist: bionic
before_install:
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - sudo apt-get install libscotch-dev
  - sudo apt-get install libopenblas-dev liblapacke-dev
  - wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2 -O eigen-3.3.7.tar.bz2 && mkdir eigen && tar -xvf eigen-3.3.7.tar.bz2 -C eigen --strip-components 1
language: cpp
compiler:
  - g++
  - clang++
env:
  global:
    - TTOR_ROOT="${HOME}/build/leopoldcambier/tasktorrent"
    - EIGEN3_ROOT="${HOME}/build/leopoldcambier/tasktorrent/eigen"
    - ASAN_OPTIONS="detect_leaks=0"
    - TTOR_MPIRUN="mpirun -oversubscribe"
    - TTOR_LARGE_TESTS="OFF"
    - TTOR_MANY_RANKS="OFF"
  jobs:
    - TTOR_TEST="MINIAPPS"
    - TTOR_TEST="TESTSUITE" TTOR_SHARED="ON"  TTOR_BUILD_TYPE="Debug"   TTOR_SAN="OFF"
    - TTOR_TEST="TESTSUITE" TTOR_SHARED="OFF" TTOR_BUILD_TYPE="Debug"   TTOR_SAN="OFF"

install:
script:
  - ./tests/test_travis.sh
