sudo: required
dist: bionic
before_install:
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - sudo apt-get install libscotch-dev
  - sudo apt-get install libopenblas-dev liblapacke-dev
  - wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2 -O eigen-3.3.7.tar.bz2 && mkdir eigen && tar -xvf eigen-3.3.7.tar.bz2 -C eigen --strip-components 1
language: cpp
compiler:
  - g++
env:
  global:
    - TTOR_ROOT="${HOME}/build/leopoldcambier/tasktorrent"
    - EIGEN3_ROOT="${HOME}/build/leopoldcambier/tasktorrent/eigen"
    - ASAN_OPTIONS="detect_leaks=0"
    - TTOR_MPIRUN="mpirun -oversubscribe"
  jobs:
    - TEST="MINIAPPS"
    - TEST="TESTSUITE" SHARED="ON" SAN="UB"
    - TEST="TESTSUITE" SHARED="ON" SAN="OFF"
    - TEST="TESTSUITE" SHARED="ON" SAN="ADDRESS"
    - TEST="TESTSUITE" SHARED="OFF" SAN="OFF"
    - TEST="TESTSUITE" SHARED="OFF" SAN="UB"
    - TEST="TESTSUITE" SHARED="OFF" SAN="ADDRESS"
install:
script:
  - ./tests/test_travis.sh
