sudo: required
dist: bionic
before_install:
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - sudo apt-get install libscotch-dev
  - sudo apt-get install libopenblas-dev liblapacke-dev
  - wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2 -O eigen-3.3.7.tar.bz2 && mkdir eigen && tar -xvf eigen-3.3.7.tar.bz2 -C eigen --strip-components 1
language: cpp
compiler:
  - g++
install:
script:
  - cd ${HOME}/build/leopoldcambier/tasktorrent/tutorial && make clean && make run
  - cd ${HOME}/build/leopoldcambier/tasktorrent/miniapp/dense_cholesky && cp Makefile.conf.travis Makefile.conf && make clean && make cholesky && mpirun -n 2 ./cholesky
  - cd ${HOME}/build/leopoldcambier/tasktorrent/miniapp/3d_gemm && cp Makefile.conf.travis Makefile.conf && make clean && make 3d_gemm && mpirun --oversubscribe -n 8 ./3d_gemm
  - cd ${HOME}/build/leopoldcambier/tasktorrent/miniapp/sparse_cholesky && cp Makefile.conf.travis Makefile.conf && make clean && make snchol && mpirun -n 2 ./snchol neglapl_2_32.mm 10 2 0 5 0 NONE 5
  
  - cd ${HOME}/build/leopoldcambier/tasktorrent && EIGEN3_ROOT=${HOME}/build/leopoldcambier/tasktorrent/eigen ./tests/test_all.sh $(pwd) ON OFF
  - cd ${HOME}/build/leopoldcambier/tasktorrent && EIGEN3_ROOT=${HOME}/build/leopoldcambier/tasktorrent/eigen ./tests/test_all.sh $(pwd) ON UB
  - cd ${HOME}/build/leopoldcambier/tasktorrent && ASAN_OPTIONS=detect_leaks=0 EIGEN3_ROOT=${HOME}/build/leopoldcambier/tasktorrent/eigen ./tests/test_all.sh $(pwd) ON ADDRESS  
  
  - cd ${HOME}/build/leopoldcambier/tasktorrent && TTOR_MPIRUN="mpirun -oversubscribe" EIGEN3_ROOT=${HOME}/build/leopoldcambier/tasktorrent/eigen ./tests/test_all.sh $(pwd) OFF OFF
  - cd ${HOME}/build/leopoldcambier/tasktorrent && TTOR_MPIRUN="mpirun -oversubscribe" EIGEN3_ROOT=${HOME}/build/leopoldcambier/tasktorrent/eigen ./tests/test_all.sh $(pwd) OFF UB
  - cd ${HOME}/build/leopoldcambier/tasktorrent && TTOR_MPIRUN="mpirun -oversubscribe" ASAN_OPTIONS=detect_leaks=0 EIGEN3_ROOT=${HOME}/build/leopoldcambier/tasktorrent/eigen ./tests/test_all.sh $(pwd) OFF ADDRESS
