GTEST_INCDIR = $(HOME)/Softwares/googletest/googletest/include
GTEST_LIBDIR = $(HOME)/Softwares/googletest/googletest/lib
BOOST_INCDIR = $(HOME)/Softwares/boost_1_67_0/
EIGEN_INCDIR = $(HOME)/Softwares/eigen
SCOTCH_INCDIR = $(HOME)/Softwares/scotch_6.0.6/include
SCOTCH_LIBDIR = $(HOME)/Softwares/scotch_6.0.6/lib
BLAS_INCDIR  = /usr/local/opt/openblas/include/
BLAS_LIBDIR  = /usr/local/opt/openblas/lib/

LIBS =
LDFLAGS =
CC = g++
CFLAGS = -Wextra -Wall --std=c++11 -O3